[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "AlphaMachine_core"
version = "0.1.0"
description = "ASM Engine core library"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
include = ["AlphaMachine_core*", "utils*"]
